[deploy]
bucket = 'cfn-artifacts-911'
region = 'us-east-1'
stack_name = 'CrdSrvFrontend'

[parameters]
CertificateArn = 'arn:aws:acm:us-east-1:470836252788:certificate/b1df22de-6474-40be-a480-410a0ae46340'      
WWWBucketName = 'www.7lawa911.com'
RootBucketName = '7lawa911.com'

